FROM node:16-alpine
WORKDIR /app
COPY common ./common
WORKDIR /app/common
RUN npm ci
WORKDIR /app
COPY client ./client
COPY tsconfig.json ./
WORKDIR /app/client
RUN npm ci && npm run build
EXPOSE 8080
CMD npm run start -- -p 8080